config/routes.rb
AdventureWorks::Application.routes.draw do
  
  resources :employees do
    
  end

  root :to => 'employees#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  
  
  


end

app/models/employee.rb
class Employee < ActiveRecord::Base

  validates_presence_of :national_id_number


end

app/models/employee_department_history.rb
class EmployeeDepartmentHistory < ActiveRecord::Base
  
  
  


end

app/models/employee_pay_history.rb
class EmployeePayHistory < ActiveRecord::Base
  
  
  


end

app/models/employees_addresses.rb
class EmployeesAddresses < ActiveRecord::Base

  belongs_to :employee
  # belongs_to :address


end

app/models/job_candidate.rb
class JobCandidate < ActiveRecord::Base

  belongs_to :employee


end

app/models/shift.rb
class Shift < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to @employee, :notice => 'Employee was successfully created.'
    else
      render :action => 'new'
    end
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to @employee, :notice => 'Employee was successfully updated.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    redirect_to employees_url
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ol>
    <li>
      <%= f.label :national_id_number, 'National ID', :class => 'required' %>
      <%= f.text_field :national_id_number %>
    </li>
    <li>
      <%= f.label :title, 'Title', :class => 'required' %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :login_id, 'Login ID', :class => 'required' %>
      <%= f.text_field :login_id %>
    </li>
  </ol>
  <fieldset class="buttons">
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing Employees</h1>

<table>
  <tr>
    <th>National ID</th>
    <th>Name</th>
    <th>Title</th>
    <th>Login ID</th>
    <th>Actions</th>
  </tr>
  <% @employees.each do |employee| %>
  <tr>
    <td><%= employee.national_id_number %></td>
    <td>TODO</td>
    <td><%= employee.title %></td>
    <td><%= employee.login_id %></td>
    <td>
      <%= link_to 'Show', employee %>
      <%= link_to 'Edit', edit_employee_path(employee) %>
      <%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %>
    </td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdventureWorks.Ruby</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="scallfold_body">
    <%= yield %>
  </div>
</body>
</html>